Fixes the Dolphin link and changes the RA build to the MESA one.
XboxDevStore/XboxDevStore.github.io pull request #13
Opened 2024-04-19 17:54 UTC by Jeenvries

2024-05-09 17:46 UTC, Jeenvries commented
Wake up

2024-06-20 17:06 UTC, jmorlock02 approved these changes

2024-06-23 06:29 UTC, jmorlock02 approved these changes

2024-06-23 06:30 UTC, jmorlock02 requested changes

2024-06-23 06:30 UTC, jmorlock02 commented on index.html
> -                                <a href="https://drive.google.com/drive/folders/1zu_DEpQzEJ-L9UYiViVUXjkFygtnxWDv?usp=drive_link" class="col-md-4 mb-md-0 mb-3 btn btn-secondary bg-success">Download A
```

```

2024-06-25 00:01 UTC, jmorlock02 approved these changes

2024-06-25 02:18 UTC, jmorlock02 approved these changes

2024-09-09 13:17 UTC, closed without merging